// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-crypto.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

import { PaymentRequest } from './messages-common';

export enum KvOperationType {
    KvOperation_Add = 1,
    KvOperation_Update = 2,
    KvOperation_Delete = 3,
}

export type EnumKvOperationType = Static<typeof EnumKvOperationType>;
export const EnumKvOperationType = Type.Enum(KvOperationType);

export type CipheredKeyValue = Static<typeof CipheredKeyValue>;
export const CipheredKeyValue = Type.Object(
    {
        value: Type.String(),
    },
    { $id: 'CipheredKeyValue' },
);

export type CipherKeyValue = Static<typeof CipherKeyValue>;
export const CipherKeyValue = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        key: Type.String(),
        value: Type.String(),
        encrypt: Type.Optional(Type.Boolean()),
        ask_on_encrypt: Type.Optional(Type.Boolean()),
        ask_on_decrypt: Type.Optional(Type.Boolean()),
        iv: Type.Optional(Type.String()),
    },
    { $id: 'CipherKeyValue' },
);

export type ECDHSessionKey = Static<typeof ECDHSessionKey>;
export const ECDHSessionKey = Type.Object(
    {
        session_key: Type.String(),
        public_key: Type.Optional(Type.String()),
    },
    { $id: 'ECDHSessionKey' },
);

export type IdentityType = Static<typeof IdentityType>;
export const IdentityType = Type.Object(
    {
        proto: Type.Optional(Type.String()),
        user: Type.Optional(Type.String()),
        host: Type.Optional(Type.String()),
        port: Type.Optional(Type.String()),
        path: Type.Optional(Type.String()),
        index: Type.Optional(Type.Number()),
    },
    { $id: 'IdentityType' },
);

export type GetECDHSessionKey = Static<typeof GetECDHSessionKey>;
export const GetECDHSessionKey = Type.Object(
    {
        identity: IdentityType,
        peer_public_key: Type.String(),
        ecdsa_curve_name: Type.Optional(Type.String()),
    },
    { $id: 'GetECDHSessionKey' },
);

export type KvAuthority = Static<typeof KvAuthority>;
export const KvAuthority = Type.Object(
    {
        schema_version: Type.Number(),
        public_key: Type.String(),
    },
    { $id: 'KvAuthority' },
);

export type KvGetAuthority = Static<typeof KvGetAuthority>;
export const KvGetAuthority = Type.Object({}, { $id: 'KvGetAuthority' });

export type KvGetRecordId = Static<typeof KvGetRecordId>;
export const KvGetRecordId = Type.Object(
    {
        key: Type.String(),
    },
    { $id: 'KvGetRecordId' },
);

export type KvHead = Static<typeof KvHead>;
export const KvHead = Type.Object(
    {
        schema_version: Type.Number(),
        seq: Type.Number(),
        records_root: Type.String(),
        prev_head_hash: Type.Optional(Type.String()),
        signature: Type.String(),
    },
    { $id: 'KvHead' },
);

export type KvRecordId = Static<typeof KvRecordId>;
export const KvRecordId = Type.Object(
    {
        record_id: Type.String(),
    },
    { $id: 'KvRecordId' },
);

export type KvSignedTransition = Static<typeof KvSignedTransition>;
export const KvSignedTransition = Type.Object(
    {
        new_head: KvHead,
    },
    { $id: 'KvSignedTransition' },
);

export type KvSparseMerkleProof = Static<typeof KvSparseMerkleProof>;
export const KvSparseMerkleProof = Type.Object(
    {
        leaf_key: Type.String(),
        leaf_hash: Type.Optional(Type.String()),
        sibling_hashes: Type.Array(Type.String()),
        exists: Type.Boolean(),
        sibling_bitmap: Type.Optional(Type.String()),
    },
    { $id: 'KvSparseMerkleProof' },
);

export type KvSignTransition = Static<typeof KvSignTransition>;
export const KvSignTransition = Type.Object(
    {
        operation: EnumKvOperationType,
        key: Type.String(),
        old_head: KvHead,
        old_value: Type.Optional(Type.String()),
        new_value: Type.Optional(Type.String()),
        proof: KvSparseMerkleProof,
        proposed_new_root: Type.String(),
    },
    { $id: 'KvSignTransition' },
);

export type PaymentNotification = Static<typeof PaymentNotification>;
export const PaymentNotification = Type.Object(
    {
        payment_req: Type.Optional(PaymentRequest),
    },
    { $id: 'PaymentNotification' },
);

export type SignedIdentity = Static<typeof SignedIdentity>;
export const SignedIdentity = Type.Object(
    {
        address: Type.String(),
        public_key: Type.String(),
        signature: Type.String(),
    },
    { $id: 'SignedIdentity' },
);

export type SignIdentity = Static<typeof SignIdentity>;
export const SignIdentity = Type.Object(
    {
        identity: IdentityType,
        challenge_hidden: Type.Optional(Type.String()),
        challenge_visual: Type.Optional(Type.String()),
        ecdsa_curve_name: Type.Optional(Type.String()),
    },
    { $id: 'SignIdentity' },
);
